// Export DOCX endpoint
const exportChannel = async (req, res) => {
  try {
    const { summary, keyPoints, originalText } = req.body;
    
    if (!summary) {
      return res.status(400).json({ error: 'Summary is required for export' });
    }

    // RTF format content
    const rtfContent = `{\\rtf1\\ansi\\deff0 
            {\\fonttbl {\\f0\\fswiss Arial;}{\\f1\\fmodern Courier New;}}
            {\\colortbl;\\red65\\green124\\blue126;\\red0\\green0\\blue0;}
            \\f0\\fs24

            {\\cf1\\b\\fs36 SUMMARY REPORT\\par}
            \\par
            {\\b Generated on: ${new Date().toLocaleDateString()}\\par}
            \\par\\par

            {\\cf1\\b\\fs28 SUMMARY\\par}
            \\par
            ${summary.replace(/\n/g, '\\par ')}
            \\par\\par

            {\\cf1\\b\\fs28 KEY POINTS\\par}
            \\par
            ${keyPoints && keyPoints.length > 0 ? 
            keyPoints.map((point, i) => `${i + 1}. ${point}\\par `).join('') : 
            'No key points available\\par '
            }

            \\par
            {\\i Generated by AppleDesk}
    }`;

    res.setHeader('Content-Type', 'application/rtf');
    res.setHeader('Content-Disposition', 'attachment; filename="summary.rtf"');
    res.send(rtfContent);

  } catch (error) {
    console.error('Export error:', error);
    res.status(500).json({ error: 'Export failed: ' + error.message });
  }
};

module.exports = exportChannel;
